# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import calculations_pb2 as calculations__pb2


class CalculationsServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Area = channel.unary_unary(
        '/CalculationsService/Area',
        request_serializer=calculations__pb2.CalculationsRequest.SerializeToString,
        response_deserializer=calculations__pb2.CalculationsResponse.FromString,
        )
    self.Volume = channel.unary_unary(
        '/CalculationsService/Volume',
        request_serializer=calculations__pb2.CalculationsRequest.SerializeToString,
        response_deserializer=calculations__pb2.CalculationsResponse.FromString,
        )


class CalculationsServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Area(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Volume(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CalculationsServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Area': grpc.unary_unary_rpc_method_handler(
          servicer.Area,
          request_deserializer=calculations__pb2.CalculationsRequest.FromString,
          response_serializer=calculations__pb2.CalculationsResponse.SerializeToString,
      ),
      'Volume': grpc.unary_unary_rpc_method_handler(
          servicer.Volume,
          request_deserializer=calculations__pb2.CalculationsRequest.FromString,
          response_serializer=calculations__pb2.CalculationsResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'CalculationsService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
